apiVersion: v1
kind: ConfigMap
metadata:
  name: cinema-config
  namespace: cinema
data:
  PORT: "3000"
  REDIS_URL: "redis://cinema-redis:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://cinema-otel-collector:4318"
  NODE_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinema-nginx
  namespace: cinema
data:
  nginx.conf: |
    events {}
    http {
      upstream cinema_backend {
        least_conn;
        server cinema-web:3000;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://cinema_backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /api/ {
          proxy_pass http://cinema_backend;
        }
        location /metrics {
          proxy_pass http://cinema_backend;
        }
      }
    }
